# Generated by Django 3.2.17 on 2023-02-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favourites',
            new_name='favorites',
        ),
    ]
